version: 2.1

executors:
  toolbox-executor:
    docker:
      - image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/toolbox:latest
        aws_auth:
          aws_access_key_id: ${AWS_ACCESS_KEY_ID}
          aws_secret_access_key: ${AWS_SECRET_ACCESS_KEY}
jobs:
  deploy:
    executor: toolbox-executor
    parameters:
      environment:
        type: enum
        enum:
          ["demo", "ops", "dev", "qa", "demo", "uat", "sit", "pre-prod", "prod"]
      weight:
        type: enum
        enum: ["small", "medium", "large"]
      ssh_db_connection:
        type: boolean
        default: false
      auto_scale:
        type: boolean
        default: false
    steps:
      - checkout
      - run:
          name: Creating infrastructure and deploying stack
          environment:
            ENVIRONMENT: << parameters.environment >>
            EKS_WEIGHT: << parameters.weight >>
            PROJECT_NAME: admin-unbiasly
            DOMAIN_NAME: eazyfin.com
            CIRCLECI_TAG: << pipeline.git.tag >>
            SERVICE_NAME: admin-unbiasly-v1
            SSH_DB_CONNECTION: << parameters.ssh_db_connection >>
            AUTO_SCALING: << parameters.auto_scale >>
            PORT: 80
          command: |
            source /ops/comman-functions.sh
            install_common_dependencies
            validate_aws_credetails
            create_vpc
            bash /ops/cd/infra-pipeline.sh /ops/cd `pwd`/ops/cd /ops/comman-functions.sh
  deploy_stack:
    executor: toolbox-executor
    parameters:
      environment:
        type: enum
        enum:
          ["demo", "ops", "dev", "qa", "demo", "uat", "sit", "pre-prod", "prod"]
      weight:
        type: enum
        enum: ["small", "medium", "large"]
      ssh_db_connection:
        type: boolean
        default: false
      auto_scale:
        type: boolean
        default: false
    steps:
      - checkout
      - run:
          name: Creating infrastructure and deploying stack
          environment:
            ENVIRONMENT: << parameters.environment >>
            EKS_WEIGHT: << parameters.weight >>
            PROJECT_NAME: admin-unbiasly
            DOMAIN_NAME: eazyfin.com
            SERVICE_NAME: admin-unbiasly-v1
            SSH_DB_CONNECTION: << parameters.ssh_db_connection >>
            AUTO_SCALING: << parameters.auto_scale >>
            PORT: 80
          command: |
            source /ops/comman-functions.sh
            install_common_dependencies
            validate_aws_credetails
            get_version_tag
            create_vpc
            bash /ops/cd/infra-pipeline.sh /ops/cd `pwd`/ops/cd /ops/comman-functions.sh

workflows:
  build-and-deploy:
    jobs:
      - deploy:
          name: deploy_dev
          environment: dev
          weight: large
          context: DevelopmentAutomation
          auto_scale: true
          filters:
            &filters-staging # this yaml anchor is setting these values to "filters-staging"
            tags:
              only:
                - /1.0.*/
            branches:
              ignore: /.*/
      - approval:
          name: qa_approval
          type: approval
          requires:
            - deploy_dev
          filters:
            <<: *filters-staging # this is calling the previously set yaml anchor
      - deploy:
          name: deploy_qa
          environment: qa
          weight: large
          context: QaAutomation
          auto_scale: true
          requires:
            - qa_approval
          filters:
            <<: *filters-staging # this is calling the previously set yaml anchor
      - deploy:
          name: deploy_qa_prod
          environment: qa
          weight: large
          context: QaAutomation
          auto_scale: true
          filters:
            &filters-production # this yaml anchor is setting these values to "filters-staging"
            tags:
              only:
                - /^v.*/
            branches:
              ignore: /.*/
      - approval:
          name: pre_prod_approval
          type: approval
          requires:
            - deploy_qa_prod
          filters:
            <<: *filters-production # this is calling the previously set yaml anchor
      - deploy:
          name: deploy_pre_prod
          environment: pre-prod
          weight: large
          context: PreProdAutomation
          auto_scale: true
          requires:
            - pre_prod_approval
          filters:
            <<: *filters-production # this is calling the previously set yaml anchor
      - approval:
          name: prod_approval
          type: approval
          requires:
            - deploy_pre_prod
          filters:
            <<: *filters-production # this is calling the previously set yaml anchor
      - deploy:
          name: deploy_prod
          environment: prod
          weight: large
          context: ProdAutomation
          auto_scale: true
          requires:
            - prod_approval
          filters:
            <<: *filters-production # this is calling the previously set yaml anchor
